/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "t.h"

bool_t
xdr_stringentry (XDR *xdrs, stringentry *objp)
{

	 if (!xdr_string (xdrs, &objp->item, 1024))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (stringentry), (xdrproc_t) xdr_stringentry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_stringlist (XDR *xdrs, stringlist *objp)
{

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (stringentry), (xdrproc_t) xdr_stringentry))
		 return FALSE;
	return TRUE;
}

int main() {
    int i;
    xdr_destroy((XDR *)NULL);
    i=2;
    i=0;
    return i;

}
