/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "t.h"

bool_t
xdr_stringentry (XDR *xdrs, stringentry *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->item, 1024))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (stringentry), (xdrproc_t) xdr_stringentry))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_stringlist (XDR *xdrs, stringlist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (stringentry), (xdrproc_t) xdr_stringentry))
		 return FALSE;
	return TRUE;
}
